jobs:
  ormolu:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v1"
      - id: setup-haskell-cabal
        uses: "actions/setup-haskell@v1.1.4"
        with:
          cabal-version: "${{ matrix.cabal }}"
          enable-stack: false
          ghc-version: "${{ matrix.ghc }}"
      - name: Cache
        uses: "actions/cache@v2"
        with:
          key: "${{ runner.os }}-${{ matrix.ghc }}-cabal"
          path: |
            ~/.local/bin
            ~/.cabal/bin
            "${{ steps.setup-haskell-cabal.outputs.cabal-store }}"
            # (I'm sure there is an environment variable somewhere
            # that points to /home/runner.)
      - name: Install dependencies
        run: |
          ls -alF ~/.cabal/bin/
          ls -alF ~/.local/bin/
          export PATH=$PATH:$HOME/.cabal/bin:$HOME/.local/bin
          export ORMOLU_VERSION=$(cat ./layout/ormolu.version)
          echo $PATH
          ~/.cabal/bin/ormolu -v
          ormolu -v
          (ormolu -v 2>/dev/null | grep -q $ORMOLU_VERSION) || (cabal update && cabal install ormolu --constraint="ormolu ==$ORMOLU_VERSION")
          test -e $HOME/.local/bin/yq || pip3 install yq
        shell: bash
      - name: Ormolu
        run: |
          export PATH=$PATH:$HOME/.cabal/bin:$HOME/.local/bin
          ./layout/ormolu.sh -c
        shell: bash
    strategy:
      matrix:
        cabal:
          - '3.2'
        ghc:
          - '8.10.1'
name: Ormolu
on:
  - pull_request
